import random
def TheQuoteBook(quote = random.randint(1, 190)):

    TQB = { # The Quote Book
        1: "Strong minds discuss ideas, average minds discuss events, weak minds discuss people",
        2: "Death can have me when it earns me",
        3: "Don’t count the days, make the days count",
        4: "Courage is not the absence of fear, it’s the ability to overcome fear",
        5: "If you never have expectations, you will never be disappointed",
        6: "Pain will leave you once it’s done teaching you",
        7: "When you build in silence, people don’t know what to attack [Move in silence, only speak when it’s time to say]",
        8: "No one is coming to save you, so save yourself before it’s too late [get up be your own hero]",
        9: "If they weren’t with you at the bottom, they can’t be with you at the top",
        10: "Rule #2, never give up [you are closer than you think]",
        11: "If you believe it will work out, you’ll see opportunities…If you believe it won’t you will see obstacles",
        12: "Rule #1 do not compare yourself to others",
        13: "The most important days in your life are the day you were born and the day you find out why",
        14: "[Don’t rush the process] Trust the process",
        15: "Never make a decision while you’re in your emotions",
        16: "Those who are more successful have failed the most",
        17: "Everything we see is a perspective not the truth",
        18: "I am not what happened to me, I am what I chose to become",
        19: "Never trust a friend who is silent about your flaws [a true friend will call you out to your face]",
        20: "We have two lives, the second begins when we realize we only have one",
        21: "Accept what you can’t change, change what you can’t accept",
        22: "Motivation will get you started, but without discipline, you will never finish",
        23: "I don’t know what I’ve been shown, loves a lie we die alone",
        24: "Lies travel faster than the truth",
        25: "Focus on improving yourself, not proving yourself",
        26: "The little wins add up, consistency over everything",
        27: "Rule 69: Instead of thinking about how hard your journey is, think about how great your story will be",
        28: "Obsession is a gift, life is to short for realistic goals",
        29: "You don’t need more time, you need less distractions",
        30: "Nobody else on this planet sees the world through your eyes, so don’t let anyone tell you how to feel [stay true to yourself]",
        31: "Prepare for the storm, if you never learn how to survive in hard times, you will always be at the mercy of your environment",
        32: "Its ok to be misunderstood, people will judge whether you go for you dreams or you do nothing at all",
        33: "Don’t let other people make you feel guilty for doing what makes you happy",
        34: "You go through life being told that justice exists, then you learn that the only real justice is the justice you take",
        35: "In between where you are and where you want to be, you are gonna doubt yourself a lot, but the only way to get to the other side is through the fire [it’s ok to cough until the smoke clears, because when it does, you’ll be able to breathe again]",
        36: "Nothing in the future is part of your reality yet, so you don’t need to worry about it [don’t carry tomorrows load with today’s strength]",
        37: "You can’t control other people’s actions, you can only control your own reactions",
        38: "Being ready is a lie, perfect timing doesn’t exist",
        39: "Whoever told you that you weren’t enough, didn’t know you at all. If they did, they would’ve seen the spark in your eyes and the light in your soul. They would’ve seen the dark times that you’ve been through. And how you shine brighter now because of it. If they really knew you, they would’ve known that you’ve always been enough.",
        40: "Those who talk behind your back, are behind you for a reason",
        41: "In Fortnite, metal takes longer to build but it’s stronger in the end",
        42: "Life is like a sky-base, as soon as they see you at the top, they want to shoot you down",
        43: "If you go into to the storm for more loot, you’ll get hurt even more",
        44: "Be more concerned with your character than your reputation. Reputation is how others see you, character is how you see yourself.",
        45: "Your future you needs you, your past you doesn’t.",
        46: "No man ever stepped into a River twice, for the river would no longer be the same, and he would not be the same man.",
        47: "If you want something you’ve never had, you must be willing to do something you’ve never done.",
        48: "One tree can make 1000 matches, but one match can burn 1000 trees",
        49: "Fear has killed more dreams than failure ever did",
        50: "Whenever you feel like quitting, just remember why you started",

        51: "You shouldn’t climb a mountain so that the world can see you, you should climb it so that you can see the world",
        52: "You can always trust a dishonest person to be dishonest. It’s the honest ones that are unpredictable",
        53: "You can’t go back and change the beginning, but you can start now and change the ending",
        54: "If I'd have never hit rock bottom Would I be the person that I am today? I don't believe so I'm a prime example of what happens when you choose to not accept defeat and face your demons",
        55: "The best time to start taking control of your life was yesterday, the next best time is now",
        56: "When the devil keeps asking you to look into the past, there’s something in the future he doesn’t want you to see",
        57: "Worrying doesn’t take away tomorrow’s trouble, it takes away tomorrow’s peace",
        58: "The prettiest smiles had the deepest secrets, the prettiest eyes have cried the most tears, the kindest hearts have felt the most pain",
        59: "Only the dead have seen the end of war",
        60: "Only a Sith deals in absolutes",
        61: "You’ll find that many of the truths we cling to depend greatly on our own point of view",
        62: "You don’t get mats from breaking down other people’s builds",
        63: "In order to make commitments, you have to make sacrifices",
        64: "Worrying doesn’t take away tomorrow’s trouble, it takes away todays peace",
        65: "Non Ducor Duco",
        66: "Someone graduated at the age of 22, but waited 5 years before securing a good job. Someone became a CEO at 25 and died at 50. Another became a CEO at 50 and lived to 90 years. Someone is still single, while someone from his school group has become a grandfather. Obama retired at 55 and Trump started at 70. Everyone on this world works based on their own timezone. People around you might seem ahead of you and some might seem behind you. But everyone is running their own race in their own time. Do not envy them. They are in their timezone and you are in yours. So relax, you’re not late, you’re not early. You are very much on time.",
        67: "Money doesn’t change you, it amplifies the person you already are.",
        68: "What’s up danger",
        69: "Listen, the journey isn’t going to be a smooth sale. Expect storms, rough waves, and maybe even a few sea monsters. But, you my friend, you’re a captain. And what does a captain do? They navigate through it all to reach their destination.",
        70: "Care less and you’ll stress less",
        71: "Failure inspires winners. Failure defeats losers.",
        72: "The first to apologize is the bravest, the first to forgive is the strongest, the first to forget is the happiest",
        73: "Forgive others not because they deserve forgiveness, but because you deserve peace",
        74: "It’s easier to justify stupidity with a group of friends.",
        75: "Become impossible to replace",
        76: "Remember kids, you marry her whole family",
        77: "A YouTuber with 10 million subscribers wouldn’t laugh at you for struggling to get views on your channel. A billionaire wouldn’t laugh at you for struggling to start a new business. Those who have are successful have failed the most.",
        78: "More often then not, the problem is not that the problems we face can not be solved, the problem is that we become so afraid of failure that we refuse to see our problems from a new perspective. And so we do the same things again and again and again. And then of course we find the exact failure we were looking for.",
        79: "Your life will always be a struggle, and you will always have problems, but today you have the chance to see things differently. When you see things from every angle and understood them for what they really were. You kept moving forward, no matter how far off the path you were told you were headed, or how unexpected it became, You found your way.",
        80: "Every time someone says a lie, for something to happen, someone would have to buy the lie. How did they fall for this",
        81: "I’m am not in danger Skyler, I am the danger",
        82: "That’s all it is Miles, a leap of faith",
        83: "Our family doesn’t run from things",
        84: "Be surprised what you find when you go outside your comfort zone.",
        85: "It’s amazing what a little bit of faith can do if you don’t even believe in you, why would think or expect anybody else that’s around you to",
        86: "Never back down, Never what?",
        87: "24/7 365 at a million percent",
        88: "We can’t undo a move, but we can make the next one better",
        89: "Most people in bad situations would be better off in worse situations because if it’s not bad enough then they wouldn’t do anything to change it",
        90: "Be yourself; everyone else is already taken",
        91: "Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.",
        92: "Insanity is doing the same thing, over and over again, but expecting different results.",
        93: "Every step I’ve ever taken in a wrong direction helped me get to where I am today",
        94: "No matter how strong love is, anger is the strongest emotion",
        95: "You just have to lock in",
        96: "People who immediately respond to your texts are not desperate. People who immediately respond to your call are not desperate, people who are always there for you when you need them are not always free or jobless. Maybe they understand how it feels to be ignored. Maybe they know what it feels like to be left alone. Because maybe they were left alone when they needed someone. Never take them for granted. They are gold.",
        97: "You heard the saying `If it’s not broke don’t fix it,’ that’s my motto",
        98: "You forget about 1000 things every day, how about you make sure this is one of them",
        99: "Always bet on black",
        100: "Remember, memories are made now, not later",

        101: "Whenever you see something like this, look left first cause shit ain’t right",
        102: "Growing pain is a necessary evil",
        103: "Motivation fades, discipline persists",
        104: "You shouldn’t take advice from people who are not where you want to be in life",
        105: "Only way to go is go the distance",
        106: "If you make it a piece of your armor, your enemies can’t hurt you with it",
        107: "It’s the lows in life that make you cherish the highs",
        108: "I got my own shoes I ain’t tryna fit in yours",
        109: "Your limits should always tend towards infinity",
        110: "In clash Royale, the best chests take the longest to unlock.",
        111: "Sometimes you have to push the past away to make room for the future",
        112: "If opportunity doesn’t knock, build a door",
        113: "The biggest mistake a person can do, right now, no matter what situation you are in, is to give up",
        114: "The smaller the circle, the better the people",
        115: "People with scars are the strongest",
        116: "Temptation is a motherfucker",
        117: "Under pressure, you don’t rise to the occasion, you sink to the level of your training",
        118: "There are no champions in love and war, just those who lose the least",
        119: "It’s okay to walk alone. It might be discouraging sometimes, but letting go of toxic people will be the most liberating thing you can do for your soul",
        120: "The truth is, some people just don’t want to see you succeed. They’d rather see you fail. Because the new version of you makes them feel uncomfortable",
        121: "Even dark knights have dark nights",
        122: "The problem is, I’m inevitable",
        123: "People will come into a discussion with their minds already made up. Cognitive dissonance",
        124: "Do you even remember what the issue is, you just tryna find where the tissue is",
        125: "Squealing louder won’t help your case pig",
        126: "You have to unlearn everything that was taught to you out of someone else’s fears and insecurities. Your purpose is about serving others through the unique abilities that were given to you.",
        127: "Peace between men will never be certain, not until our numbers fall to 1 or less",
        128: "We all had to spend our lives drunk on something, we all were a slave to something",
        129: "Don’t waist your teenage years trying to find love",
        130: "If you’re not constant state of post nut clarity, you’re in a constant state of pre nut delusion",
        131: "Don’t fight other people, fight what you’re going through",
        132: "Sodium Hydride, Iodine Deuterium, Tungsten Iodide Nitride",
        133: "It only takes once",
        134: "It’s not that hard to overcome these seemingly ghastly times, what’s hard is to decide",
        135: "It’s not your job to fulfill somebody else’s needs of who they want you to be, give yourself the freedom to live a life that feels right to you.",
        136: "Don’t be discouraged by the distance between where you are and where you want to be. just focus on the next step. It’s time to prove to yourself just how capable you are.",
        137: "If everything seems dark, you may be the light",
        138: "Be nice for no reason.",
        139: "Let your past be a lesson, not a life sentence",
        140: "The only realities we live in are the ones we apply to ourselves",
        141: "One bad game doesn’t mean you should stop playing",
        142: "The people who are used to playing small are going to be intimidated when you start showing some audacity and when you start owning who you are and what you came to do. They will criticize they will challenge. And they will doubt everything you do. So keep showing up exactly as you are.",
        143: "It’s not a loss if you learned something",
        144: "It’s easier to live a life you hate, than it is to live a life you love",
        145: "Don’t stare at money too long, it’s Medusa",
        146: "No one can decide what struggle success looks like in someone else’s life, you get to chose that",
        147: "Word to wise, before you embark on a journey for revenge, dig two graves",
        148: "If you have an idea that you think is genuinely good, don’t let some idiot talk you out of it",
        149: "In my experience, who people are supposed to be, is rarely who they are",
        150: "Diligence is the mother of good luck",

        151: "One please burger cheese?",
        152: "No amount of evidence will ever persuade an idiot",
        153: "When a person thinks they have no choice, is when you see their true character",
        154: "I can’t make it make sense, ‘cause they making dollars off that non sense",
        155: "Your life will change when you decided to change it, when you set standards for yourself and accept nothing less…because change doesn’t come from someone else, the only person capable of giving you permission to turn your life around is you",
        156: "So you see relationships where one person is a masterful liar and the other person is completely oblivious. THAT is Stalin…Beware",
        157: "Diplomacy is you telling someone to go to hell, and then looking forward to the trip",
        158: "Winners never quit, quitters never win",
        159: "Once you start learning, the L disappears",
        160: "Pressure is a privilege",
        161: "It is delusion to think your actions have had any consequence",
        162: "If you love what you are doing more than the outcome of what you are doing, then there is no such thing as failure",
        163: "I know boners often conquer red flags, but maybe they shouldn’t!",
        164: "The only way to move on is to move on whether you think you are ready to or not, gotta get out there man",
        165: "To reach the End you must go through hell",
        166: "Sometimes losing people is part of life, but that doesn’t mean you stop letting them in",
        167: "Prepare and prevent, not repair and repent",
        168: "I feel like the luckiest man alive and… I feel like a fool. That woman confuses me and plays me for a fiddle like no one else alive. I trust I will not make a god awful fool of my self once more but, somehow I imagine I shall.",
        169: "Preparation can imo take you so far, after that you need to take a few leaps of faith.",
        170: "It's hard to wait around for something you know might never happen, but it's harder to give up when you know it's everything you want",
        171: "I understand the impulse to pull the trigger, but if we lose ourselves we lose everything",
        172: "Sometimes the people we save, they save us right back",
        173: "You can do anything you set your mind to man",
        174: "The effect you have on people, is the most valuable currency there is",
        175: "We all have our private life, our public life. And your secret life, the one that defines you",
        176: "It’s not about how fast you get there, it’s about staying in the game long enough to win",
        177: "Time isn’t your enemy, it’s your greatest ally, but it only works for you if you show up",
        178: "I understand it now",
        179: "People won’t care how much you know, until they know how much you care",
        180: "You have to be odd to be number one",
        181: "Not ever thought deserves your belief",
        182: "Most of whats running through your mind is just fear pretending to be logic",
        183: "Don’t let one mistake make you forget all the times you got it right",
        184: "The longer you know somebody, the more cursed you are to see them as human.",
        185: "No amount of money ever bought a second of time",
        186: "Which way does a tree fall…A Tree falls the way it leans, be careful which way you lean",
        187: "Nothing weakens you more than hate, nothing elevates you more than understanding",
        188: "The only person who never makes a mistake, is a person who does nothing",
        189: "One act of kindness will inspire another",
        190: "A winner is just a loser who tried one more time"
    }
    return f'Quote #{quote}: "{TQB[quote]}"'


if __name__ == "__main__":
    print(TheQuoteBook(67))
    print()
    print("Random quote:")
    print(TheQuoteBook())
